#!/usr/bin/env python3
"""The boot menu's font (device/menu/font.h), rasterised from Inter for the round panel.

disc-menu draws text from 8-bit alpha masks: the player's toolchain has no font
rasteriser, so the masks are made here, once, from Inter (SIL Open Font
License 1.1; device/licenses/Inter.OFL) and the generated header is kept with
the sources. The menu is always in English and titles are printable ASCII, so
ASCII and the few signs the screen uses are enough.

    python3 scripts/menu_font.py --font <Inter[opsz,wght].ttf> --output device/menu/font.h

Pillow (with FreeType) renders the masks; the header records the font's SHA-256
and the Pillow and FreeType versions it was made with.
"""
import argparse
import hashlib
from pathlib import Path

from PIL import Image, ImageFont, features

SOURCE = 'https://github.com/google/fonts/raw/main/ofl/inter/Inter%5Bopsz,wght%5D.ttf'
# The faces the menu's screen uses (owner's choice of the list layout, 2026-10-03).
FACES = [('label', 'SemiBold', 13), ('title', 'Regular', 20), ('title_bold', 'SemiBold', 20),
         ('small', 'Regular', 12), ('note', 'Regular', 13)]
SIGNS = [0x00B1, 0x00B7, 0x2026, 0x25B6]          # ± · … ▶
CODES = list(range(0x20, 0x7F)) + SIGNS


def face(path, weight, size):
    f = ImageFont.truetype(str(path), size)
    f.set_variation_by_name(weight)
    return f


def glyph(f, code):
    """The mask, its top-left from the pen on the baseline, and the advance in 1/64 pixel."""
    ch = chr(code)
    advance = round(f.getlength(ch) * 64)
    if ch == ' ':
        return b'', 0, 0, 0, 0, advance
    mask, (ox, oy) = f.getmask2(ch, mode='L', anchor='ls')
    w, h = mask.size
    image = Image.frombytes('L', (w, h), bytes(mask)) if w and h else None
    if image is None or not image.getbbox():
        return b'', 0, 0, 0, 0, advance
    # Trim the empty margin around the mask, keeping its place.
    left, top, right, bottom = image.getbbox()
    image = image.crop((left, top, right, bottom))
    return image.tobytes(), ox + left, oy + top, right - left, bottom - top, advance


def generate(font_path, output):
    data = Path(font_path).read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    alpha = bytearray()
    lines = []
    tables = []
    for name, weight, size in FACES:
        f = face(font_path, weight, size)
        ascent, descent = f.getmetrics()
        rows = []
        for code in CODES:
            bits, x, y, w, h, advance = glyph(f, code)
            if not (-128 <= x < 128 and -128 <= y < 128 and w < 256 and h < 256):
                raise ValueError(f'{name}: glyph {code:#x} does not fit the table')
            rows.append(f'    {{0x{code:04x}, {x}, {y}, {w}, {h}, {advance}, {len(alpha)}}},')
            alpha += bits
        lines.append(f'static const menu_glyph glyphs_{name}[] = {{\n' + '\n'.join(rows) + '\n};')
        tables.append(f'    {{"{name}", {size}, {ascent}, {descent}, {len(CODES)}, glyphs_{name}}},')
    hexed = ',\n'.join('    ' + ','.join(f'{b}' for b in alpha[i:i + 24]) for i in range(0, len(alpha), 24))
    text = f'''/* Generated by scripts/menu_font.py; do not edit. Inter (SIL Open Font License 1.1,
   device/licenses/Inter.OFL), {SOURCE},
   SHA-256 {digest}; rendered with Pillow {Image.__version__}, FreeType {features.version_module('freetype2')}. */
#ifndef DISC_MENU_FONT_H
#define DISC_MENU_FONT_H
/* A glyph: its code point, its mask's top-left from the pen on the baseline, its size,
   the pen's advance in 1/64 pixel, and where its mask starts in menu_alpha. */
typedef struct {{ unsigned short code; signed char x, y; unsigned char w, h; unsigned short advance64; unsigned int offset; }} menu_glyph;
typedef struct {{ const char *name; int size, ascent, descent, count; const menu_glyph *glyphs; }} menu_face;

static const unsigned char menu_alpha[] = {{
{hexed}
}};

{chr(10).join(lines)}

static const menu_face menu_faces[] = {{
{chr(10).join(tables)}
}};
#endif
'''
    Path(output).write_text(text)
    return dict(font=digest, faces=[n for n, _, _ in FACES], glyphs=len(CODES), alphaBytes=len(alpha))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--font', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    print(generate(args.font, args.output))
